### ISSUE TITLE
Using   animationIn  and animationOut

### ISSUE THREAD

**Issue by Code4Zelda** [react-native-modal/react-native-modal#356]
## Ask your Question

When using the animation, there is a delay/skip once the modal gets in the middle of the screen then finishes opening perfectly.  Im only passing data to this component from the parent . Nothing is being fetch from anywhere when i call for this component. What could be the problem here?

These are the props I'm using. As you can see for the style i used marginVert and marginHori so that the modal can fix the whole screen.

 <Modal
        isVisible={this.props.visible}
        animationIn="slideInRight"
        animationOut="slideOutRight"
        coverScreen
        style={{ marginHorizontal: 0, marginVertical: 0 }}
      >

**Comment by bhaveshdaswani93** [comment]
you can use useNativeDriver={true} and hideModalContentWhileAnimating={true}
and also there is note while using native driver 

> The modal flashes in a weird way when animating
Unfortunately this is a known issue that happens when useNativeDriver=true and must still be solved.
In the meanwhile as a workaround you can set the hideModalContentWhileAnimating prop to true: this seems to solve the issue. Also, do not assign a backgroundColor property directly to the Modal. Prefer to set it on the child container.

https://github.com/react-native-community/react-native-modal#the-modal-flashes-in-a-weird-way-when-animating

so your overall code would look like this
`<Modal
isVisible={this.props.visible}
animationIn="slideInRight"
animationOut="slideOutRight"
coverScreen
style={{ marginHorizontal: 0, marginVertical: 0 }}
useNativeDriver={true}
hideModalContentWhileAnimating={true}
>`
