### ISSUE TITLE
wrapping SafeAreaView in the children node

### ISSUE THREAD

**Issue by yeong0809** [react-native-modal/react-native-modal#394]
## Environment

System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 66.25 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.6.0 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 27, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-19 | Google APIs Intel x86 Atom, android-21 | Google APIs Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom_64
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-create-library: 3.1.2

## Platforms

iOS: iPhone 5s 10.3.1 and iPhones 7 Plus 10.3.1
Android: No problem

## Versions

- iOS:
- react-native-modal: 11.5.3
- react-native: 0.61.5
- react: 16.9.0

## Description

The modal did not show the child content

## Reproducible Demo

        <RNModal
          isVisible={this.state.isVisible}
        >
          <SafeAreaView style={{ flex: 1 }}>
            <View style={{ backgroundColor: "white", flex: 1 }}>
              <Text>
                { "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc"
                }
              </Text>
            </View>
          </SafeAreaView>
        </RNModal>

**Comment by yeong0809** [comment]
It seems to be happened only when the animationIn is set to "slideInUp"

**Comment by jasonbodily** [comment]
Same problem here, except on the first time it works. On subsequent tries it doesn't. ios 13.3, iphone 11.

**Comment by rewieer** [comment]
Tried locally, found no problems. It's probably related to the native modal directly.

**Comment by caiangums** [comment]
Hey @yeong0809 ! I think I have something that can help. The possible issue is that you are not passing a size to the `<Modal />` component neither to your `<SafeAreaView />` component.

I suggest using `Dimensions` from React Native lib or reading [this section at Readme](https://github.com/react-native-community/react-native-modal#the-backdrop-is-not-completely-filledcovered-on-some-android-devices-galaxy-for-one) about size of things inside the modal.

Try this:
```jsx
<RNModal
  isVisible={true}
  deviceWidth={deviceWidth} {/* here */}
  deviceHeight={deviceHeight} {/* and here */}
  style={{ margin: 0, flex: 1 }}>
  <SafeAreaView style={{ flex: 1 }}> {/* here you can pass backgroundColor: "white" too, if you want */}
    <View style={{ backgroundColor: "white", flex: 1 }}>
      <Text>{"Test Text"}</Text>
    </View>
  </SafeAreaView>
</RNModal>
```

Another possible solution is defining your `zIndex` from your modal as `2` or `3`. You should hardly avoid using `zIndex` property at Styles but for this case is ok because it's supposed to show the content in front of other content.

**Comment by jagwingchoy** [comment]
Hi everyone, I have encountered the same problem as @yeong0809 met, and I found **a solution** for this!

## Situation
- This issue only happens on iOS 10.3.1 or below regardless of iPhone type
- If using `<View/>` to replace `<SafeAreaView/>`, the layout will be fine 
- If changing `animationIn` from `slideInUp` to any other animation that not includes Y-axis change will also be fine

### My thought
It should be a native bug and fixed on iOS 11.0.0.  
I have tested that this bug is also happening on other `<SafeAreaView />`'s animation that moving Y-axis from bottom, 
no matter using `translateY` or `bottom` style.

📢 　  **Until Apple officially announces not supporting iOS 10 or below,　　　　　📢
📢 　please help to spread this message to other projects that are also affected.** 📢

## Screenshots
<img src="https://user-images.githubusercontent.com/58965922/99755998-14589280-2b27-11eb-90b2-1831c04393dc.jpg" width="250" /><img src="https://user-images.githubusercontent.com/58965922/99756240-aa8cb880-2b27-11eb-98e6-262da344d162.jpg" width="250" /><img src="https://user-images.githubusercontent.com/58965922/99756279-c001e280-2b27-11eb-8b5c-a3d6013dc412.jpg" width="250" />

## My Codes

### IOSModal/index.js
<details><summary>Click to expand</summary>  

    import React, { PureComponent } from 'react';
    import { SafeAreaView, TouchableOpacity, View, Text } from 'react-native';
    import Modal from 'react-native-modal';
    import PropTypes from 'prop-types';

    import { I18n } from '@Helpers';
    import { COLORS } from '@Styles';

    import { styles } from './styles';

    class IOSModal extends PureComponent {
    state = { visible: false };

    show = () => {
      this.props.onShow && this.props.onShow();
      this.setState({ visible: true });
    };

    hide = () => { this.setState({ visible: false }); };

    submit = () => {
      this.props.onSubmit && this.props.onSubmit();
      this.hide();
    };

    render() {
      return (
        <Modal style={styles.modal} testID="modal" isVisible={this.state.visible} onRequestClose={this.hide} onBackdropPress={this.hide} transparent>
          <SafeAreaView style={styles.modalBox}>
            <View style={styles.header}>
              <TouchableOpacity style={styles.button} onPress={this.hide}>
                <Text style={styles.cancel}>{I18n.t('cancel')}</Text>
              </TouchableOpacity>
              <TouchableOpacity style={styles.button} onPress={this.submit}>
                <Text style={styles.submit}>{I18n.t('submit')}</Text>
              </TouchableOpacity>
            </View>

            <View style={styles.content}>
              {this.props.children && this.props.children}
            </View>
          </SafeAreaView>
        </Modal>
      );
    }
    }

    IOSModal.propTypes = {
      children: PropTypes.element.isRequired,
      onShow: PropTypes.func,
      onSubmit: PropTypes.func
    };

    export default IOSModal;
</details>

### IOSModal/styles.js
<details><summary>Click to expand</summary>  

    import { StyleSheet } from 'react-native';

    import { COLORS } from '@Styles';

    export const styles = StyleSheet.create({
      modal: {
        margin: 0,
        justifyContent: 'flex-end'
      },
      modalBox: {
        borderTopLeftRadius: 15,
        borderTopRightRadius: 15,
        width: '100%',
        backgroundColor: COLORS.IOS_MODAL.BACKGROUND
      },
      header: {
        borderBottomWidth: 0.3,
        borderBottomColor: COLORS.INPUT.BORDER,
        paddingHorizontal: 15,
        paddingVertical: 8,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center'
      },
      button: {
        paddingVertical: 9,
        paddingHorizontal: 15
      },
      cancel: {
        fontSize: 17,
        color: COLORS.TEXT
      },
      submit: {
        fontSize: 17,
        color: COLORS.THEME.PRIMARY
      },
      content: {
        justifyContent: 'center'
      }
    });
</details>

## Solutions

#### 1. Create this custom slideInUp animation:
    const newSlideInUp = {
      0: {
        opacity: 0,
        translateY: 0
      },
      0.5: {
        opacity: 0,
        translateY: 100,
      },
      1: {
        opacity: 1,
        translateY: 0,
      }
    };

#### 2. Use it in your modal component's `animationIn`:  

    <Modal animationIn={newSlideInUp} style={styles.modal} isVisible={this.state.visible}>
      {/*...*/}
    </Modal>

#### 3. Or you can add it to modal's `defaultProps` if your modal mostly use default `animationIn`:

     import Modal from 'react-native-modal';

     Modal.defaultProps = Modal.defaultProps || {};
     Modal.defaultProps.animationIn = newSlideUp;

**Comment by mmazzarolo** [comment]
Closing, thank you @jagwingchoy !

**Comment by ucheNkadiCode** [comment]
None of these solutions worked for me. I've tried wrapping every single component in safearea view, I've tried using device height and device width. I am still having to use paddingBottom to get my buttons up above the safe are inset. Does anyone have another way of doing this? 

Thank you!
