### ISSUE TITLE
Can you add swipe in right and swipe out left animated modal example?

### ISSUE THREAD

**Issue by NagashreeMedaMN** [react-native-modal/react-native-modal#439]
All other examples are there except for this.

**Comment by mmazzarolo** [comment]
Hi! 
I'm closing this issue because it's a question and not a bug report. Please don't take it personally, I'm just trying to make it easier to maintain this project by separating questions from bug reports 🙏.  
If you're still looking for feedback/answers, could you please ask your question in a new [discussion](https://github.com/react-native-modal/react-native-modal/discussions)?  
Thank you!
