### ISSUE TITLE
not close when clicking mouse.

### ISSUE THREAD

**Issue by dsagredo** [react-native-modal/react-native-modal#441]
## Ask your Question

Hello, I want to know, 
How the modal will not close when clicking outside it. Click the button below to try it?

**Comment by mmazzarolo** [comment]
Hi! 
I'm closing this issue because it's a question and not a bug report. Please don't take it personally, I'm just trying to make it easier to maintain this project by separating questions from bug reports 🙏.  
If you're still looking for feedback/answers, could you please ask your question in a new [discussion](https://github.com/react-native-modal/react-native-modal/discussions)?  
Thank you!
