### ISSUE TITLE
Package is Unrealeased

### ISSUE THREAD

**Issue by hbiede** [react-native-modal/react-native-modal#499]
## Description

The package has not released newly merged PRs.

**Comment by mmazzarolo** [comment]
Yeah, I know, I'm very sorry but the CI (which should automatically release the package updates) is not working correctly anymore since `react-native-modal` was moved out of the community org last month. 
I do have plans to move the CI to GitHub actions as soon as I have some free time -- hopefully this weekend. 
In the meanwhile, you can target the master branch of this repo in your package.json to get the latest version. I will ping you back in this thread when the package is released.

**Comment by mmazzarolo** [comment]
@hbiede done 👍

**Comment by hbiede** [comment]
Thanks so much!
