### ISSUE TITLE
I install  react-native-modal failed

### ISSUE THREAD

**Issue by Syrena-GitHub** [react-native-modal/react-native-modal#500]
error Couldn't find package "react-native-animatable@1.3.3" required by "react-native-modal" on the "npm" registry.

How can I solve this problem??

**Comment by 09azAZ** [comment]
the same as you，looking...

**Comment by mmazzarolo** [comment]
Hi! 
I'm closing this issue because it's a question and not a bug report. Please don't take it personally, I'm just trying to make it easier to maintain this project by separating questions from bug reports 🙏.  
If you're still looking for feedback/answers, could you please ask your question in a new [discussion](https://github.com/react-native-modal/react-native-modal/discussions)?  
Thank you!
