### ISSUE TITLE
Modal height

### ISSUE THREAD

**Issue by Talha-Jawed** [react-native-modal/react-native-modal#518]
i implement modal height in style props but height does'nt apply .. show the full screen height modal still

**Comment by mmazzarolo** [comment]
Hi! 
I'm closing this issue because it's a question and not a bug report. Please don't take it personally, I'm just trying to make it easier to maintain this project by separating questions from bug reports 🙏.  
If you're still looking for feedback/answers, could you please ask your question in a new [discussion](https://github.com/react-native-modal/react-native-modal/discussions)?  
Thank you!

**Comment by kutsan** [comment]
You could probably easily convert this issue into a discussion and maybe give an answer there.

**Comment by dqii** [comment]
https://github.com/react-native-modal/react-native-modal/discussions/628
