### ISSUE TITLE
ReactNativeModal Ref Attribute

### ISSUE THREAD

**Issue by IvKr95** [react-native-modal/react-native-modal#558]
## Ask your Question

My goal is to close the current modal and open another one immediately.
I tried to get it working by using setTimeout but this approach didn't work out.
Then I tried to save a reference of a modal in order to listen to onModalHide event but the ref does not seem to exist.
Is there such a thing as a ref attribute on ReactNativeModal or would you please suggest a better workaround?

**Comment by NathanBeesley** [comment]
There are other ways to achieve this but I created a quick snack for you to see. Make sure you test it on a device or select iOS/Android from the device preview. It looks goofy on web otherwise.

https://snack.expo.io/@nathanbeesley/react-native-modal

Let me know if this is what you were looking for.
