### ISSUE TITLE
modal in iOS not getting dismissed after setting isVisible prop to false

### ISSUE THREAD

**Issue by hk22sync** [react-native-modal/react-native-modal#560]
I have a custom Loader component designed using ActivityIndicator and react-native-modal.

**Loader.js**
```
import React, {PureComponent} from 'react';
import PropTypes from 'prop-types';
import { StyleSheet, View, ActivityIndicator } from 'react-native';
import Modal from 'react-native-modal';

class Loader extends PureComponent {
  static propTypes = {
    loading: PropTypes.bool
  }
  constructor(props) {
    super(props);
  }
  render() {
    return(<Modal
      isVisible = {this.props.loading}
    >
      <View style={styles.modalBackground}>
        <View style={styles.activityIndicatorWrapper}>
          <ActivityIndicator animating={!!this.props.loading} size={'large'} />
        </View>
      </View>
    </Modal>);
  }
}

```

**Parent Component: App.js** 
```
import React from 'react';
import { Loader } from './Loader.js';

class App extends PureComponent {

  constructor(props) {
    super(props);
    this.state = { loading: false}
  }

 getData = async () => {
    this.setState({loading: true}); 
    let response = await APIcall();
    this.setState({loading: false});
}

  render() {
    return(
     <View>
        <Loader props = {this.state.loading}>
    </View>

);
  }
}
```
The function getData is called on a user interaction.
loading state is set to true --> Modal opens
API call is made
loading prop is set to false --> Modal stays on the screen

react version: 16.9.0,
react-native version: 0.61.2,
iOS version: iPadOS 13.5.1

**Comment by NathanBeesley** [comment]
Is there a reason you are making your api call inside of a render function? I think that should be inside a lifecycle function like componentWillMount/componentDidMount.  Unless I'm missing something here. Also you should be able to in the constructor set loading true.

**Comment by NathanBeesley** [comment]
I was thinking something like this should work?

class App extends React.PureComponent {

	constructor(props) {
		super(props);
		this.state = { loading: true }
	}

	componentDidMount() {
		this.getData()
	}

	getData = async () => {
		let response = await APIcall();
		this.setState({ loading: false });
	}

	render() {
		return (
			<View>
				<Loader props={this.state.loading}>
    		</View>
		)
	}
}

**Comment by hk22sync** [comment]
> Is there a reason you are making your api call inside of a render function? I think that should be inside a lifecycle function like componentWillMount/componentDidMount. Unless I'm missing something here. Also you should be able to in the constructor set loading true.

Sorry, my bad. 
The function getData is called on a user action.

**Comment by NathanBeesley** [comment]
@hk22sync I have created a snack to test out the code you shared. I have modified it slightly. I have added a loader example with both a class based and function based component. I changed the props from 'props' in the loader class to avoid confusionI,  props have been changed  to 'loading'. I also mocked up an api call with a promise to better reflect an actual api(shouldn't take 5 seconds but there just to visually give it time to load then hide). Also after doing all this I noticed the double negate operand here: <ActivityIndicator animating={**!!this.props.loading**} size={'large'} /> which is causing a race condition. You are setting state and immediately resetting it since setState is async. Either way change it to this 
<ActivityIndicator animating={!this.props.loading} size={'large'} /> or you can see my example in the following Expo Snack. 

https://snack.expo.io/@nathanbeesley/happy-cashew

**Comment by liupengandroid** [comment]
This question still has ah why direct turn off can't like this!
Hiding Modal immediately after displaying modal must occur

rn:^0.64.3     ios:14.4.1
