### ISSUE TITLE
how to add component in the overlay area 

### ISSUE THREAD

**Issue by FatmaMahmoud698** [react-native-modal/react-native-modal#569]
how to make component with zIndex in the transparent area

**Comment by mmazzarolo** [comment]
Hi! 
I'm closing this issue because it's a question and not a bug report. Please don't take it personally, I'm just trying to make it easier to maintain this project by separating questions from bug reports 🙏.  
If you're still looking for feedback/answers, could you please ask your question in a new [discussion](https://github.com/react-native-modal/react-native-modal/discussions)?  
Thank you!
